language: r
sudo: false
cache: packages


warnings_are_errors: true

matrix:
  include:
    - os: linux
      language: r
      compiler: gcc
      env: TRAVIS_LANG=R     
    
    - os: linux
      language: r
      compiler: clang
      env: TRAVIS_LANG=R     
 
 
r_check_args: "--as-cran"

