# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnorm2 <- function(x, mean, sigma, lwr, logd, A) {
    .Call('bssm_dmvnorm2', PACKAGE = 'bssm', x, mean, sigma, lwr, logd, A)
}

uv_filter <- function(y, Z, HH, T, RR, C, at, Pt, zero_tol) {
    .Call('bssm_uv_filter', PACKAGE = 'bssm', y, Z, HH, T, RR, C, at, Pt, zero_tol)
}

intervals <- function(means, sds, probs, n_ahead) {
    .Call('bssm_intervals', PACKAGE = 'bssm', means, sds, probs, n_ahead)
}

bsm_loglik <- function(model_) {
    .Call('bssm_bsm_loglik', PACKAGE = 'bssm', model_)
}

bsm_filter <- function(model_) {
    .Call('bssm_bsm_filter', PACKAGE = 'bssm', model_)
}

bsm_fast_smoother <- function(model_) {
    .Call('bssm_bsm_fast_smoother', PACKAGE = 'bssm', model_)
}

bsm_sim_smoother <- function(model_, nsim, seed) {
    .Call('bssm_bsm_sim_smoother', PACKAGE = 'bssm', model_, nsim, seed)
}

bsm_smoother <- function(model_) {
    .Call('bssm_bsm_smoother', PACKAGE = 'bssm', model_)
}

bsm_ccov_smoother <- function(model_) {
    .Call('bssm_bsm_ccov_smoother', PACKAGE = 'bssm', model_)
}

bsm_predict2 <- function(model_, prior_types, prior_pars, n_iter, n_burnin, n_thin, gamma, target_acceptance, S, n_ahead, interval, seed, log_space) {
    .Call('bssm_bsm_predict2', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, n_burnin, n_thin, gamma, target_acceptance, S, n_ahead, interval, seed, log_space)
}

bsm_predict <- function(model_, prior_types, prior_pars, n_iter, n_burnin, n_thin, gamma, target_acceptance, S, n_ahead, interval, probs, seed, log_space) {
    .Call('bssm_bsm_predict', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, n_burnin, n_thin, gamma, target_acceptance, S, n_ahead, interval, probs, seed, log_space)
}

bsm_particle_filter <- function(model_, nsim_states, seed) {
    .Call('bssm_bsm_particle_filter', PACKAGE = 'bssm', model_, nsim_states, seed)
}

bsm_particle_filter2 <- function(model_, nsim_states, seed, bootstrap) {
    .Call('bssm_bsm_particle_filter2', PACKAGE = 'bssm', model_, nsim_states, seed, bootstrap)
}

bsm_particle_smoother <- function(model_, nsim_states, seed, fs) {
    .Call('bssm_bsm_particle_smoother', PACKAGE = 'bssm', model_, nsim_states, seed, fs)
}

bsm_backward_simulate <- function(model_, nsim_states, seed, nsim_store) {
    .Call('bssm_bsm_backward_simulate', PACKAGE = 'bssm', model_, nsim_states, seed, nsim_store)
}

bsm_run_mcmc <- function(model_, prior_types, prior_pars, n_iter, sim_states, n_burnin, n_thin, gamma, target_acceptance, S, seed, log_space, end_ram) {
    .Call('bssm_bsm_run_mcmc', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, sim_states, n_burnin, n_thin, gamma, target_acceptance, S, seed, log_space, end_ram)
}

bsm_run_mcmc_summary <- function(model_, prior_types, prior_pars, n_iter, n_burnin, n_thin, gamma, target_acceptance, S, seed, log_space, end_ram) {
    .Call('bssm_bsm_run_mcmc_summary', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, n_burnin, n_thin, gamma, target_acceptance, S, seed, log_space, end_ram)
}

gssm_loglik <- function(model_) {
    .Call('bssm_gssm_loglik', PACKAGE = 'bssm', model_)
}

gssm_filter <- function(model_) {
    .Call('bssm_gssm_filter', PACKAGE = 'bssm', model_)
}

gssm_fast_smoother <- function(model_) {
    .Call('bssm_gssm_fast_smoother', PACKAGE = 'bssm', model_)
}

gssm_sim_smoother <- function(model_, nsim, seed) {
    .Call('bssm_gssm_sim_smoother', PACKAGE = 'bssm', model_, nsim, seed)
}

gssm_smoother <- function(model_) {
    .Call('bssm_gssm_smoother', PACKAGE = 'bssm', model_)
}

gssm_run_mcmc <- function(model_, prior_types, prior_pars, n_iter, sim_states, n_burnin, n_thin, gamma, target_acceptance, S, seed, end_ram, Z_ind, H_ind, T_ind, R_ind) {
    .Call('bssm_gssm_run_mcmc', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, sim_states, n_burnin, n_thin, gamma, target_acceptance, S, seed, end_ram, Z_ind, H_ind, T_ind, R_ind)
}

gssm_run_mcmc_summary <- function(model_, prior_types, prior_pars, n_iter, n_thin, n_burnin, gamma, target_acceptance, S, seed, end_ram, Z_ind, H_ind, T_ind, R_ind) {
    .Call('bssm_gssm_run_mcmc_summary', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, n_thin, n_burnin, gamma, target_acceptance, S, seed, end_ram, Z_ind, H_ind, T_ind, R_ind)
}

gssm_predict <- function(model_, prior_types, prior_pars, n_iter, n_burnin, n_thin, gamma, target_acceptance, S, n_ahead, interval, Z_ind, H_ind, T_ind, R_ind, probs, seed) {
    .Call('bssm_gssm_predict', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, n_burnin, n_thin, gamma, target_acceptance, S, n_ahead, interval, Z_ind, H_ind, T_ind, R_ind, probs, seed)
}

gssm_predict2 <- function(model_, prior_types, prior_pars, n_iter, n_burnin, n_thin, gamma, target_acceptance, S, n_ahead, interval, Z_ind, H_ind, T_ind, R_ind, seed) {
    .Call('bssm_gssm_predict2', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, n_burnin, n_thin, gamma, target_acceptance, S, n_ahead, interval, Z_ind, H_ind, T_ind, R_ind, seed)
}

gssm_particle_filter <- function(model_, nsim_states, seed) {
    .Call('bssm_gssm_particle_filter', PACKAGE = 'bssm', model_, nsim_states, seed)
}

gssm_particle_smoother <- function(model_, nsim_states, seed, method) {
    .Call('bssm_gssm_particle_smoother', PACKAGE = 'bssm', model_, nsim_states, seed, method)
}

gssm_backward_simulate <- function(model_, nsim_states, seed, nsim_store) {
    .Call('bssm_gssm_backward_simulate', PACKAGE = 'bssm', model_, nsim_states, seed, nsim_store)
}

ng_bsm_loglik <- function(model_, init_signal, nsim_states, method, seed, max_iter, conv_tol) {
    .Call('bssm_ng_bsm_loglik', PACKAGE = 'bssm', model_, init_signal, nsim_states, method, seed, max_iter, conv_tol)
}

ng_bsm_filter <- function(model_, init_signal) {
    .Call('bssm_ng_bsm_filter', PACKAGE = 'bssm', model_, init_signal)
}

ng_bsm_fast_smoother <- function(model_, init_signal) {
    .Call('bssm_ng_bsm_fast_smoother', PACKAGE = 'bssm', model_, init_signal)
}

ng_bsm_sim_smoother <- function(model_, nsim, init_signal, seed) {
    .Call('bssm_ng_bsm_sim_smoother', PACKAGE = 'bssm', model_, nsim, init_signal, seed)
}

ng_bsm_smoother <- function(model_, init_signal) {
    .Call('bssm_ng_bsm_smoother', PACKAGE = 'bssm', model_, init_signal)
}

ng_bsm_run_mcmc <- function(model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, end_ram, adapt_approx, da, sim_type) {
    .Call('bssm_ng_bsm_run_mcmc', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, end_ram, adapt_approx, da, sim_type)
}

ng_bsm_run_mcmc_is <- function(model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, n_threads, end_ram, adapt_approx, sim_type, const_m, seeds) {
    .Call('bssm_ng_bsm_run_mcmc_is', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, n_threads, end_ram, adapt_approx, sim_type, const_m, seeds)
}

ng_bsm_run_mcmc_summary <- function(model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, n_threads, end_ram, adapt_approx, da, sim_type) {
    .Call('bssm_ng_bsm_run_mcmc_summary', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, n_threads, end_ram, adapt_approx, da, sim_type)
}

ng_bsm_run_mcmc_summary_is <- function(model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, n_threads, end_ram, adapt_approx, sim_type, const_m, seeds) {
    .Call('bssm_ng_bsm_run_mcmc_summary_is', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, n_threads, end_ram, adapt_approx, sim_type, const_m, seeds)
}

ng_bsm_predict2 <- function(model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, n_ahead, interval, init_signal, seed, log_space) {
    .Call('bssm_ng_bsm_predict2', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, n_ahead, interval, init_signal, seed, log_space)
}

ng_bsm_importance_sample <- function(model_, init_signal, nsim_states, seed) {
    .Call('bssm_ng_bsm_importance_sample', PACKAGE = 'bssm', model_, init_signal, nsim_states, seed)
}

ng_bsm_approx_model <- function(model_, init_signal, max_iter, conv_tol) {
    .Call('bssm_ng_bsm_approx_model', PACKAGE = 'bssm', model_, init_signal, max_iter, conv_tol)
}

ng_bsm_particle_filter <- function(model_, nsim_states, seed, bootstrap, init_signal) {
    .Call('bssm_ng_bsm_particle_filter', PACKAGE = 'bssm', model_, nsim_states, seed, bootstrap, init_signal)
}

ng_bsm_particle_smoother <- function(model_, nsim_states, seed, method, type, init_signal) {
    .Call('bssm_ng_bsm_particle_smoother', PACKAGE = 'bssm', model_, nsim_states, seed, method, type, init_signal)
}

ng_bsm_backward_simulate <- function(model_, nsim_states, seed, nsim_store) {
    .Call('bssm_ng_bsm_backward_simulate', PACKAGE = 'bssm', model_, nsim_states, seed, nsim_store)
}

ngssm_loglik <- function(model_, init_signal, nsim_states, method, seed, max_iter, conv_tol) {
    .Call('bssm_ngssm_loglik', PACKAGE = 'bssm', model_, init_signal, nsim_states, method, seed, max_iter, conv_tol)
}

ngssm_filter <- function(model_, init_signal) {
    .Call('bssm_ngssm_filter', PACKAGE = 'bssm', model_, init_signal)
}

ngssm_fast_smoother <- function(model_, init_signal) {
    .Call('bssm_ngssm_fast_smoother', PACKAGE = 'bssm', model_, init_signal)
}

ngssm_sim_smoother <- function(model_, nsim, init_signal, seed) {
    .Call('bssm_ngssm_sim_smoother', PACKAGE = 'bssm', model_, nsim, init_signal, seed)
}

ngssm_smoother <- function(model_, init_signal) {
    .Call('bssm_ngssm_smoother', PACKAGE = 'bssm', model_, init_signal)
}

ngssm_run_mcmc <- function(model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, end_ram, adapt_approx, da, sim_type, Z_ind, T_ind, R_ind) {
    .Call('bssm_ngssm_run_mcmc', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, end_ram, adapt_approx, da, sim_type, Z_ind, T_ind, R_ind)
}

ngssm_run_mcmc_is <- function(model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, n_threads, end_ram, adapt_approx, sim_type, const_m, Z_ind, T_ind, R_ind, seeds) {
    .Call('bssm_ngssm_run_mcmc_is', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, n_threads, end_ram, adapt_approx, sim_type, const_m, Z_ind, T_ind, R_ind, seeds)
}

ngssm_predict2 <- function(model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, n_ahead, interval, Z_ind, T_ind, R_ind, init_signal, seed) {
    .Call('bssm_ngssm_predict2', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, n_ahead, interval, Z_ind, T_ind, R_ind, init_signal, seed)
}

ngssm_importance_sample <- function(model_, init_signal, nsim_states, seed) {
    .Call('bssm_ngssm_importance_sample', PACKAGE = 'bssm', model_, init_signal, nsim_states, seed)
}

ngssm_approx_model <- function(model_, init_signal, max_iter, conv_tol) {
    .Call('bssm_ngssm_approx_model', PACKAGE = 'bssm', model_, init_signal, max_iter, conv_tol)
}

ngssm_particle_filter <- function(model_, nsim_states, seed, bootstrap, init_signal) {
    .Call('bssm_ngssm_particle_filter', PACKAGE = 'bssm', model_, nsim_states, seed, bootstrap, init_signal)
}

ngssm_particle_smoother <- function(model_, nsim_states, seed, fs, bootstrap, init_signal) {
    .Call('bssm_ngssm_particle_smoother', PACKAGE = 'bssm', model_, nsim_states, seed, fs, bootstrap, init_signal)
}

ngssm_backward_simulate <- function(model_, nsim_states, seed, nsim_store) {
    .Call('bssm_ngssm_backward_simulate', PACKAGE = 'bssm', model_, nsim_states, seed, nsim_store)
}

svm_loglik <- function(model_, init_signal, nsim_states, method, seed, max_iter, conv_tol) {
    .Call('bssm_svm_loglik', PACKAGE = 'bssm', model_, init_signal, nsim_states, method, seed, max_iter, conv_tol)
}

svm_filter <- function(model_, init_signal) {
    .Call('bssm_svm_filter', PACKAGE = 'bssm', model_, init_signal)
}

svm_fast_smoother <- function(model_, init_signal) {
    .Call('bssm_svm_fast_smoother', PACKAGE = 'bssm', model_, init_signal)
}

svm_sim_smoother <- function(model_, nsim, init_signal, seed) {
    .Call('bssm_svm_sim_smoother', PACKAGE = 'bssm', model_, nsim, init_signal, seed)
}

svm_smoother <- function(model_, init_signal) {
    .Call('bssm_svm_smoother', PACKAGE = 'bssm', model_, init_signal)
}

svm_run_mcmc <- function(model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, end_ram, adapt_approx, da, sim_type, gkl) {
    .Call('bssm_svm_run_mcmc', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, end_ram, adapt_approx, da, sim_type, gkl)
}

svm_run_mcmc_is <- function(model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, n_threads, end_ram, adapt_approx, sim_type, const_m, gkl, seeds) {
    .Call('bssm_svm_run_mcmc_is', PACKAGE = 'bssm', model_, prior_types, prior_pars, n_iter, nsim_states, n_burnin, n_thin, gamma, target_acceptance, S, init_signal, seed, n_threads, end_ram, adapt_approx, sim_type, const_m, gkl, seeds)
}

svm_importance_sample <- function(model_, init_signal, nsim_states, seed) {
    .Call('bssm_svm_importance_sample', PACKAGE = 'bssm', model_, init_signal, nsim_states, seed)
}

svm_approx_model <- function(model_, init_signal, max_iter, conv_tol) {
    .Call('bssm_svm_approx_model', PACKAGE = 'bssm', model_, init_signal, max_iter, conv_tol)
}

svm_particle_filter <- function(model_, nsim_states, seed, bootstrap, init_signal) {
    .Call('bssm_svm_particle_filter', PACKAGE = 'bssm', model_, nsim_states, seed, bootstrap, init_signal)
}

svm_particle_smoother <- function(model_, nsim_states, seed, method, type, init_signal) {
    .Call('bssm_svm_particle_smoother', PACKAGE = 'bssm', model_, nsim_states, seed, method, type, init_signal)
}

svm_backward_simulate <- function(model_, nsim_states, seed, nsim_store) {
    .Call('bssm_svm_backward_simulate', PACKAGE = 'bssm', model_, nsim_states, seed, nsim_store)
}

